### ISSUE TITLE
How to enforce authentication for all routes under prefix?

### ISSUE THREAD

**Issue by moollaza** [tunnckoCore/koa-better-router#12]
@tunnckoCore first I wanted to say thanks a lot for writing this library and very thorough documentation! I'm new to Koa, and this has been very helpful.

I've been fiddling with a side project, and I was trying to determine the best way to ensure that a router with a prefix (or any router I suppose) enforces a condition to be met, like authentication.

For example, I have a router, `const router = require('koa-better-router')({ prefix: '/app' }).loadMethods();`

and several routes:

```node
// /app/home
router.get('/home', async (ctx, next) => { ... });
// /app/foo
router.get('/foo', async (ctx, next) => { ... });
// /app/bar
router.get('/bar', async (ctx, next) => { ... });
```

I could put a check in each route like so:

```node
router.get('/home', async (ctx, next) => {
    if (!authenticated) {
        ctx.redirect('/login');
    } else {
        ctx.render('..', {});
    }
    return next();
});
```

but this is very repetitive. I believe I could wrap that check in a function, but it's still somewhat repetitive, as I would have to add that function to each route.

Is there an existing simpler approach to ensure all the routes for a given router meet a condition?

Please let me know if I can clarify anything.

**Comment by tunnckoCore** [comment]
Heya @moollaza , thanks for the kind words :) I very :heart:  this package and its docs too, haha.

Do you tried to chain middlewares? I believe it is possible and that's exactly because of such purposes - auth, uploads and etc. If one middleware not match any condition, next won't be called.

What about something like that

```js
const auth = (ctx, next) => {
  if (authenticated) return next()
  ctx.redirect('/login')
  return // actually, may not be needed at all
}

const home = (ctx, next) => {
  ctx.render('foobar', { hello: 'world' })
}

router.get('/home', auth, home)
```

**Comment by moollaza** [comment]
> Or what about something like that (in this case, the opposite of the prev. sentence - "if auth is okey, call the next middleware, otherwise just not call next() ...")

Wow, that's so simple! I didn't realize I could pass along other middleware as arguments like that. 

When I looked at the docs for `koa-router`, [I saw that was possible](https://github.com/alexmingoia/koa-router/tree/master/#multiple-middleware) but couldn't find any examples for `koa-better-router`. I should have just tested it 😄 

Thanks for the quick reply and detailed example 👍

**Comment by tunnckoCore** [comment]
> Update: I've confirmed this works as expected

Cool, thanks.

It is documented in the API (the `..fns`), it can be seen in recipes too.

https://github.com/tunnckoCore/koa-better-router#createroute
https://github.com/tunnckoCore/koa-better-router#addroute
(same is for all of the HTTP verb methods like get, set, put and etc)

```js
router.addRoute('GET /users',
  (ctx, next) => {
    ctx.body = `first ${ctx.route.path};`
    return next()
  },
  function * (next) {
    this.body = `${this.body} prefix is ${this.route.prefix};`
    yield next
  },
  (ctx, next) => {
    ctx.body = `${ctx.body} and third middleware!`
    return next()
  }
)
```

each middleware returns such function. for example `koa-foobar` is `app.use(foobar())`. It is just a convention to be explicitly invoking the middlewares.

```js
const body = require('koa-better-body')
router.post('/form', body({ some: 'options to koa-better-body' }), (ctx, next) => {
}, function * (next) {
  yield next
})
```

**Comment by moollaza** [comment]
@tunnckoCore thanks again for explaining things. Not sure how I missed the `...fns` in your docs 🤦‍♂️ 

Now I understand things much more clearly 👍

**Comment by tunnckoCore** [comment]
Cool. No problem, it happens.
