### ISSUE TITLE
Should there be a way to set a default route? (not found)

### ISSUE THREAD

**Issue by DoumanAsh** [tunnckoCore/koa-better-router#13]
While looking into code i found that regardless if route is found or not, next middleware is called. So you cannot exactly be sure without examining koa context wether route is matched or not.

What do you think about adding possibility of configuring default router(i.e. 404 router)?

**Comment by tunnckoCore** [comment]
meeh.. maybe good point. i'll look at that in onw two days.

it is more correct to be  said 404 route, not router. but yea i understand.

**Comment by DoumanAsh** [comment]
I can propose PR with maybe new method `defaultRoute` which basically will just add route to be called before passing to next middleware https://github.com/tunnckoCore/koa-better-router/blob/master/index.js#L548

The most simple and straightforward way, i suppose :)

**Comment by tunnckoCore** [comment]
I'm not sure. Or at least I don't see sense to add `defaultRoute` or such method. 

Don't know, let me think it. :)

**Comment by tunnckoCore** [comment]
Koa by default send 404 if nothing happen. As about should it call the next middleware if route not found... i'm still not sure. I believe I made it the same way as `koa-router` (for example) do it, but I'll recheck.

**Comment by DoumanAsh** [comment]
The idea is to let your user to decide what to do if it cannot hit any route.
As of now user is forced to check for `ctx.route` to determine wether router found match or not.

E.g. https://github.com/DoumanAsh/lazy-http-can/blob/master/server/index.js#L22-L29

It would be good to let user customize 404 response without need to add own middleware.

> As about should it call the next middleware if route not found... 
It should.
After all user might want to have some post-processing of final response.

**Comment by tunnckoCore** [comment]
Mmm. Maybe we can add `this.options.notFound(ctx)` before the `return next()`?

**Comment by DoumanAsh** [comment]
I'll try but isn't `this.options` passed to `pathMatch`?
Would it be safe to mix options like that?

**Comment by tunnckoCore** [comment]
Yea, they are passed to `path-match` and so to `path-to-regexp`, but it is safe looking at the `path-to-regexp` code.

> Still i'm not sure it is good idea to mix options

worse idea would be to allow passing options to `.middleware` method, I tried in first releases and removed it with reason - too many entry points, too much flexibility :D 

> Code

self preference is camelCase, so PR is is welcome for that line. But please use the commit convention.

**Comment by tunnckoCore** [comment]
@DoumanAsh just published 2.1 :)

**Comment by DoumanAsh** [comment]
Thanks, wanted to do it myself, but i got a bit busy :)
