### ISSUE TITLE
Is there a way to add mutiple verb to single path?

### ISSUE THREAD

**Issue by codinggirl** [tunnckoCore/koa-better-router#64]
I need both `GET` and `POST` verb route to same path. Is there a method instead write two routes?

**Comment by tunnckoCore** [comment]
Hey, @codinggirl sorry for the late reply! It seems I missed that because of the noise of the notifications.

I don't think so. But you simply do it with something like

```js
function yourPostAndGetHandler() {}

router.get('/', yourPostAndGetHandler);
router.post('/', yourPostAndGetHandler);
```

**Comment by codinggirl** [comment]
Thank you.
